# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Source', models.CharField(max_length=200)),
                ('Destination', models.CharField(max_length=200)),
                ('Content', models.CharField(max_length=520000)),
                ('Status', models.CharField(max_length=200)),
            ],
        ),
    ]
