# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_messages_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='RealTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
